### ISSUE TITLE
No message sent when using "require confirmation"

### ISSUE THREAD

**Issue by dawiinci** [IndigoDomotics/indigo-pushover#11]
Works with e.g. "high priority". I'm using the latest version of Indigo.

This is a serious issue.

**Comment by mbendiksen** [comment]
Try v1.1.5 which I just published:

https://github.com/IndigoDomotics/indigo-pushover/releases/download/v1.1.5/indigo-pushover.1.1.5.zip

**Comment by dawiinci** [comment]
Works, thanks for the quick fix!
