### ISSUE TITLE
Allow cancelation of emergency priority (2) from Indigo

### ISSUE THREAD

**Issue by BradyRosino** [IndigoDomotics/indigo-pushover#12]
When sending a pushover message of emergency priority, Pushover will return a receipt value. Using that receipt value the API can cancel the emergency.

This would be EXTREMELY useful in the following example.

I have a trigger where if it becomes dark outside and the garage door was left open, it will send an emergency priority notification to my phone. I send emergency so it keeps pestering in case I miss the original notification. Once I close the garage door I'd love that to trigger the pushover plugin to cancel the emergency notification.

This can be done by a POST notification to

`https://api.pushover.net/1/receipts/(your receipt)/cancel.json`

This could probably just be handled by storing the latest emergency notification receipt number in an indigo variable. Then hitting the cancel trigger (or action group) would just do the POST request with that variable in the above URL.

YES - this is currently possible using Indigo timer and pesters and repeatedly sending the notification.... then cancel the pester on the resolution of the emergency. But that requires a lot more moving parts.

Appreciate this plug in, works great!

**Comment by jcs** [comment]
This could be done with [tags](https://pushover.net/api/receipts#cancel_by_tag) without having to store the receipt ID

**Comment by indigodomo** [comment]
Added in the 1.3.0 release (see above comment).

**Comment by BradyRosino** [comment]
Missed this a few months back... Thanks for following up on this! Great improvement.
