### ISSUE TITLE
Error in Indigo when using no title

### ISSUE THREAD

**Issue by dawiinci** [IndigoDomotics/indigo-pushover#24]
```
   Pushover Error                  Error in plugin execution ExecuteAction:
Traceback (most recent call last):
  File "plugin.py", line 119, in send
UnboundLocalError: local variable 'msgTitle' referenced before assignment
```
I'm using no title in the plugin - the field is left empty.
The message is sent out anyway but the error is logged.

I am not sure if this is introduced with 1.5.1, but it happens at this version.

**Comment by FlyingDiver** [comment]
It was introduced in the most recent pull request.  

Fixed in 1.5.2
