### ISSUE TITLE
startup failure 

### ISSUE THREAD

**Issue by dduff617** [IndigoDomotics/indigo-pushover#27]
Running Indigo 7.3 and Pushover 1.5.2.   Noticed that Pushover was not present in my Indigo environment, looked and discovered I was getting the following error at plugin load time:

```
   Pushover Error                  Error in plugin execution InitializeMain:

Traceback (most recent call last):
IndentationError: ('expected an indented block', ('plugin.py', 120, 10, '    \t\tself.debugLog(u"Result: %s" % r.text)\n'))

   Stopping plugin "Pushover 1.5.2" (pid 52764)
   Stopped plugin "Pushover 1.5.2"

```
looks like a trivial typo with a missing tab.  I inserted and things reloaded peacefully.   Sorry I'm don't feel confident familiar enough with checkin procedures to post a true patch...

**Comment by FlyingDiver** [comment]
It's already fixed in the 1.5.4 pre-release.
