### ISSUE TITLE
error after upgrade install

### ISSUE THREAD

**Issue by hitch31** [IndigoDomotics/indigo-pushover#28]
Apr 22, 2019 at 10:26:45 AM
   Reloading plugin "Pushover 1.5.2"
   Starting plugin "Pushover 1.5.2" (pid 62456)
   Pushover Error                  Error in plugin execution InitializeMain:

Traceback (most recent call last):
IndentationError: ('expected an indented block', ('plugin.py', 120, 10, '    \t\tself.debugLog(u"Result: %s" % r.text)\n'))

**Comment by FlyingDiver** [comment]
Use the pre-release 1.5.4 for now.

**Comment by hitch31** [comment]
I just saw this version in response to special character error. I installed 1.5.4 and do NOT get the error message anymore.
Thank you for your excellent work

**Comment by FlyingDiver** [comment]
Made 1.5.3 official for this error.  Still working on unicode issue in 1.5.4.
