### ISSUE TITLE
Feature Request: Multiple API Tokens

### ISSUE THREAD

**Issue by whmoorejr** [IndigoDomotics/indigo-pushover#29]
I'm pretty much using Pushover as my goto notification platform now.  Most of my notifications, however, are scripted to take advantage of using multiple API tokens.  I've set up several applications in my pushover account for different types of events.... Motion, Access Control, Climate, Emergency, Indigo.  

This way I can group notifications and the initial image is specific to the event category.  Previously, I would get my indigo icon followed by whatever message or image.  Now I can get a specific icon pop up on my phone / watch first, followed by the message.

I think it's a good way to prioritize.  Don't know if it's possible to add multiple pushover applications to your plugin so when you go to send, you can pick from a dropdown of your different application names.

Anyway, just a thought.

**Comment by FlyingDiver** [comment]
The UI to maintain the list of tokens is the hard part.  I'll look into it.

**Comment by whmoorejr** [comment]
Very cool.    Thank you
  

  
  

  
  
>

**Comment by FlyingDiver** [comment]
So, there's two pieces of data used to send a notification.  The "User Key" and the "API Token".  Does the user key stay the same and only the API Token change?

**Comment by whmoorejr** [comment]
Hey Joe,

Correct, I’m only changing the API Token… the user key stays the same.

But that did send me on a quest… from pushover.net <http://pushover.net/>, I set up group keys to have a separate user key for clusters (my devices, wife’s devices, domopads, computers).  But I don’t see a benefit to doing a group message this way versus just doing a coma separated list of device names….  Unless there is someone using indigo on more of a global Muti-user scale where a group can be a collection of several users, not just several devices from one user.

**Comment by mlamoure** [comment]
I know this is 7 months ago you posted this question, but you may be able to accomplish what you need via the "device" option in a pushover event in Indigo.  By default, the notification goes to all devices, unless you specify a sub-set.  Also the priority will give you a different visual for higher priority alerts.  I just checked and, yes, you can technically create multiple Apps in Pushover for Indigo, I dont think many are using the plugin / Pushover in this way.

**Comment by FlyingDiver** [comment]
Sooner or later this one will bubble up to the top.  If it's still needed.

**Comment by FlyingDiver** [comment]
Is this still needed?  I'm trying to clear up my issue backlog and I'll want to get this done if there's still a need.

**Comment by whmoorejr** [comment]
I think I'm the only one that uses multiple pushover apps to separate my pushover messages by subject.... which I currently do via python.  So, I need it, but I don't need it to be a part of your plugin.  I use the plugin for all my general home automation notifications.  
![IMG_0128](https://user-images.githubusercontent.com/24414574/107729822-89b3a980-6cb7-11eb-97b1-c732bcc80b95.PNG)

**Comment by FlyingDiver** [comment]
Can you post the script you use to send them separately?

**Comment by whmoorejr** [comment]
This script attempts to get a snapshot image from a camera.
  Success = Save the image to a file and send the success message (SMessage) with the image as attachment.
     Note: My script saves the image twice, once in a folder to have a log of all motion driven CCTV image with a unique name and as a static name "R.JPG" to use as a refreshing image URL on control pages.
  Fail = send the fail message (FMessage)
I have another version of the script that (after sending the "FMessage"), it runs another action [indigo.actionGroup.execute(123)]that has a short delay then a script to try to get the snapshot image again.  If success, send image. Else, =+1 to a variable as a loop counter and repeat the action (no fail message).  This way I get a pushover right away, hopefully with an attached image.  If there is no image at the moment, I get the fail message and then Pushover won't bother me again until the script successfully gets the image and sends it to me.  After the 5th loop, the variable is set back to 0, the action stops looping and I get a different failure message "Camera offline after 5th attempt to contact" <-- something like that.

`import requests
import datetime

####################
### Declare Variables
####################

THIS_SCRIPT = "Camera Image Frond Door to Pushover: {}"
IMAGE_PATH = "/Users/myName/Desktop/IPCamRotate/R.jpg"
IMAGE_URL = "http://CAMERA.URL:PORT/cgi-bin/snapshot.cgi?"
USER_NAME = "donkey"
USER_PASSWORD = "cheeseburger"

### Pushover User
PushUser = "useyouruserkeynotmine"

### Pushover API Tokens
IndigoToken = "a3DgNt1oJjGQ3XsWbyn1gCGgpBBJHn"
MotionToken = "aozr2vbzs95fgqqpfft5ua6o4hbonv"
FrontDoorToken = "atc7jc7p6obvz2mr42jj7qxj21nq7h"
ClimateToken = "awzppcvnt2a5g7qq763hpqevhca1sp"
CDRAToken = "aa5xf4wkxpvx1h255fga1zpafoee9a"
EmergencyToken = "a1tic3o2qk6kpox88e4ms12j98wauh"
SecurityToken = "aqszkwjywd2ie1h1tv4uwrwrdm1tfh"

### Build Success Message
Time = "{date:%Y%m%d_%H-%M-%S}".format(date=datetime.datetime.now())
Title = "FrontDoor.jpg"
SMessage = u"{}_{}".format(Time, Title)

### Build Fail Message
Title2 = "Front Door Motion: Camera Offline"
FMessage = u"{}_{}".format(Time, Title2)


# Step 1 - Make the request and get the reply. 

try:
	from requests.auth import HTTPDigestAuth
	reply = requests.get(IMAGE_URL, 
		auth=HTTPDigestAuth(USER_NAME, USER_PASSWORD),
		timeout = 2.0)
	reply.raise_for_status()      

except:
    data = { 
        "token": MotionToken,
        "user": PushUser,
        "message": FMessage
    }
    r = requests.post('https://api.pushover.net/1/messages.json', data=data)
    print(r.text)
    indigo.server.log(
		THIS_SCRIPT.format('No camera image available'),
		isError=True
    )

else:   

    # Save the content to a file
	with open(IMAGE_PATH, 'wb') as image_file:
		image_file.write(reply.content)

    # Step 2 - Create Unique filename

	FileName = u'/Users/williammoore/Desktop/IPCamLog/{}_{}'.format(Time, Title)

    # Step 3 - Save same image data to Log Image 

	with open(FileName, 'wb') as image_file:
		image_file.write(reply.content)

    # Step 4 - Send Image via pushover

	data = {
		"token": MotionToken,
		"user": PushUser,
		"message": SMessage
	}
	files = {
		"attachment": ('image.jpg', open(FileName, 'rb'), 'image/jpg')
	}
	r = requests.post("https://api.pushover.net/1/messages.json", data=data, files=files)
	print(r.text)
	indigo.server.log(
		THIS_SCRIPT.format('Successfull Run'))
`

**Comment by jcs** [comment]
@whmoorejr Please don't publicly post Pushover API tokens.

**Comment by FlyingDiver** [comment]
I grabbed the file and deleted the tokens.

**Comment by whmoorejr** [comment]
Ok, good.  I deleted it from my post above and edited it with fake tokes.  Thanks jcs for pointing it out.  (At least I remembered to take out the username and password for my cameras.) :-)

**Comment by FlyingDiver** [comment]
Try https://github.com/IndigoDomotics/indigo-pushover/releases/tag/1.6.0

**Comment by FlyingDiver** [comment]
Released for testing.  Submit bugs in new issues.
