### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by haakonfl** [IndigoDomotics/indigo-pushover#30]
Hi, thanks for a great plugin. I get this error in my log; do you know what it means? It looks similar to an earlier reported issue that was said to be fixed. I use version 1.5.3 with Indigo 7.3.

`Pushover Error                  Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 121, in send
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)
`

**Comment by FlyingDiver** [comment]
Try using https://github.com/IndigoDomotics/indigo-pushover/releases/tag/1.5.4

Let me know if that fixes it.

**Comment by haakonfl** [comment]
Thanks! I will try that.

**Comment by mlamoure** [comment]
Joe - Once maybe @haakonfl confirms, can we consider bumping this rls?  I've been using it without problems for quite some time now.  

I'm working on some usability updates that I'll want to have pulled and tested as a pre-release before a full release to the plugin store.

**Comment by FlyingDiver** [comment]
Works for me.

**Comment by FlyingDiver** [comment]
Closing this because 1.5.4 has been in the store for quite a while.  Not sure why the OP wasn't using it.
