### ISSUE TITLE
Loosing App Tokens

### ISSUE THREAD

**Issue by whmoorejr** [IndigoDomotics/indigo-pushover#33]
Pushover v. 1.7.1 on indigo 2021.1.1 
I don't know what the catalyst is.  About three times now, all my app tokens disappear.  When that happens, the plugin won't execute.  
This is what I'm setting up now to try to figure it out...

I just set up a trigger to catch an error:
SQL Logger Event -> Error in Event Log -> application token is invalid
Action: Email event log data 100 lines

And I set a schedule to send a pushover to a device that I don't listen to (so it doesn't annoy me) every two hours.

My thought is, once I get an email, I'll have a max of 2 hours of log items to sift through to try to identify what deleted the data.

Let me know if you have any thoughts on this or other ways to troubleshoot.

**Comment by whmoorejr** [comment]
Re-added tokens.  I made a mistake so I attempted to delete the mistake "IndigoToken".  I noticed that it is throwing an error.  Not sure if this is related to the auto vanishing tokens, but the plugin won't let me delete a token.

   Pushover Error                  UI dynamic list function returned illegal ID string (ignoring): 
   Pushover                        Deleting Token a3DgNt1oJjGQ3XsWbyn1gCGgpBBJHn
   Pushover Error                  Error in plugin execution UiAction:

Traceback (most recent call last):
  File "plugin.py", line 190, in deleteTokens
KeyError: (u'a3DgNt1oJjGQ3XsWbyn1gCGgpBBJHn',)

   Pushover Debug                  get_app_tokens = [(u'', u''), (u'awzppcvnt2a5g7qq763hpqevhca1sp', u'Climate'), (u'a3DgNt1oJjGQ3XsWbyn1gCGgpBBJHn', u'Indigo'), (u'a1tic3o2qk6kpox88e4ms12j98wauh', u'Emergency'), (u'a3DgNt1oJjGQ3XsWbyn1gCGgpBBJHn', u'IndigoToken'), (u'aozr2vbzs95fgqqpfft5ua6o4hbonv', u'Motion'), (u'aa5xf4wkxpvx1h255fga1zpafoee9a', u'CDRA'), (u'atc7jc7p6obvz2mr42jj7qxj21nq7h', u'FrontDoor'), (u'aqszkwjywd2ie1h1tv4uwrwrdm1tfh', u'Security')]
   Pushover Error                  UI dynamic list function returned illegal ID string (ignoring):

**Comment by FlyingDiver** [comment]
Might be because there's a duplicate in there.  Both Indigo and IndigoToken have the same key.  That shouldn't happen, so I'll have to take a look at it.

**Comment by whmoorejr** [comment]
The duplicate entry, "Indigo" & "Indigo Token" was a mistake I made today when copy/pasting my tokens back into the plugin.  I tried to delete a different token just to see what happens and it threw the same error on Line 190.

Take your time, I'm not in a hurry with it.

**Comment by FlyingDiver** [comment]
Obsoleted by Python 3 port.  Please create new issue if this is a problem with the current release.
