### ISSUE TITLE
Can't delete token

### ISSUE THREAD

**Issue by markaslett** [IndigoDomotics/indigo-pushover#34]
Flying Diver,

I am using the latest version of Pushover 1.7.1

I created a second Indigo app token by error. When I try to delete it using the MANAGE APP TOKEN menu item in the plugin, I get the following error:

Mar 26, 2022 at 9:04:03 PM
   Pushover                        Deleting Token KEY_TOKEN_TO_BE_DELETED
   Pushover Error                  Error in plugin execution UiAction:

Traceback (most recent call last):
  File "plugin.py", line 190, in deleteTokens
KeyError: (KEY_TOKEN_TO_BE_DELETED)

Many thanks, Mark

**Comment by FlyingDiver** [comment]
There's something very broken in that code.  The easiest way to fix it is to disable the plugin and delete the preferences file, then re-enable the plugin.

**Comment by markaslett** [comment]
Thanks Joe. That took care of the issue. Much appreciated. Mark

Sent from my iPhone

On Mar 26, 2022, at 9:32 PM, Joe Keenan ***@***.***> wrote:

﻿
There's something very broken in that code. The easiest way to fix it is to disable the plugin and delete the preferences file, then re-enable the plugin.
