### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by jltnol** [IndigoDomotics/indigo-pushover#37]
Dave.. this is Jeffrey from Indigo with the Twilio problem. Giving Pushover another try and looks promising. This is what I've done:
1. Sign up for a Pushover Account- 
2. Download and install the Indgio Plugin
3. Download and install the iOS app on my phone
4. Create the Indgio app on the Push website
5. Find both the API and User Key tokens from the website, and enter those into the plugin
6. Get my phone registered with the website
7. Send test message from website to phone 
So far, everything up to this point works perfectly, and I can see how this is going to be the best solution for me.

8. Setup an Indigo Action Group to send Push message, and have filled out the TITLE and MESSAGE fields,  but get this error in the Indigo Log.

Pushover Error                  Post Error - Result: {"token":"invalid","errors":["application token must be supplied, see https://pushover.net/api"],"status":0,"request":"fb1b3ca7-3177-4186-8fcd-2838aab9db7f"}

I've double checked both tokens and the ones from the website are the same as in Indigo.  I think this is where I ran into a brick wall last time. I'm guessing I'm missing a step, but can't see/find out what it might be.  I'm assuming the application token mentioned in the error message is really the API token, which I have.  I don't see any other fields in the Indigo dialog box that aren't "options". Thought I might need to create a Pushover Device, but don't see how to do that in Indigo.

**Comment by FlyingDiver** [comment]
Just to confirm, the API key you're using is from creating an application in this area of the pushover website:
<img width="1225" alt="Screenshot 2023-08-17 at 8 05 23 PM" src="https://github.com/IndigoDomotics/indigo-pushover/assets/72976/4d752051-cee8-4547-96c5-ff8cb8ff7393">

And then the user key is from the top left of that page.

Make sure you don't have them reversed.

And then your send message action looks like this:

<img width="475" alt="Screenshot 2023-08-17 at 8 08 43 PM" src="https://github.com/IndigoDomotics/indigo-pushover/assets/72976/e7680f16-234a-446b-9087-9392bf4c3310">

**Comment by jltnol** [comment]
Joe

So in all the messing around I managed to create more ‘YOUR APPS” on Pushover than necessary, but have now deleted them all to start over.

Now, with no apps, I went to this page
https://pushover.net/apps/clone/indigo_domotics￼
Left the App name the same, checked the TOS box, and clicked the Create Application.

I’m taken to a page with the API Token Key, which I’ve copied and pasted into the Pluign Config in Indigo

From the API page, I go back to the dashboard, see my user key, and copy and paste it into the Plugin config page as well, and click SAVE. 

So I’m assuming that part is right. 

Back in Indigo, I create an Action Group  Notifications - Send Pushover Notification, and fil in the Title and Message fields, and click Save, but get the same error message.  I did put the plugin into debug mode, but not sure there is much here to help:

 Action Group                    Push 22222
   Pushover Debug                  send pluginAction.props = io.thechad.indigoplugin.pushover : (dict)
     msgAttachment :  (string)
     msgBody : Message Goes Here (string)
     msgDevice :  (string)
     msgPriority : 0 (string)
     msgSound :  (string)
     msgSupLinkTitle :  (string)
     msgSupLinkUrl :  (string)
     msgTags :  (string)
     msgTitle : Title Goes hHere (string)
     msgUser :  (string)
   Pushover Error                  Post Error - Result: {"token":"invalid","errors":["application token must be supplied, see https://pushover.net/api"],"status":0,"request":"a0d83e82-d307-4997-ac32-f55dcc35dad9"}


I can easily start this all over with a new Pushover account if you think that might help…. But I’m assuming I’ve done all the steps correctly, but still get the error message… Do need to install other software for this to work, if so, I haven’t.  I only have the Pushover Plugin for Indigo.  

As always, thanks for your help!

 Jeffrey

**Comment by FlyingDiver** [comment]
How are you getting to the "Clone application" page rather than the "create application" page?  What link are you following?

**Comment by jltnol** [comment]
Was going to this url mentioned in the plugin config:   (not sure what Link I had sent previously, but meant to send this one—>)

pushover.net/apps/clone/indigo_domotics <http://pushover.net/apps/clone/indigo_domotics>

JT

First pic shows user key and the app at the bottom, 2nd pic is the page when I click on the Indigo Domotics link in Your Application  The user key and API token are what I have in the Plugin.  

Lastly, I haven’t been able to find any instructions, so if there are some that I’ve missed I should read and follow, please point me in the right direction.




￼

____________________________________________________________________________________________________________________________________________

￼

**Comment by FlyingDiver** [comment]
Don't do that.  Just create an app from the link on the pushover page, not the link in the config.  That's old, and should have been removed.

**Comment by jltnol** [comment]
So just to be clear:
I am on the main Pushover webpage.

At the bottom the last lines deal with “Your Applications”. There is a link to Create an Application/API token, which I click on. 

From there I am on the Create New Application API Token Page.

I’m asked for a NAME  (in my case using Bradford), leaving the Description URL and ICON fields empty.

I click on the TOS box, and click Create Application.

From there, I have an API Token/Key page, and I copy the key and put it into the plug-in Config back in Indigo. And click Save.

Back on the Pushover website, I’m back on the dashboard, find my user key, and copy it and past it also into the plugin config, and click Save.

In Indigo, I go back to my same Action Group, to execute, but still get the same error message.

****************************************
Minutes later— Decided to delete the plugin, stop the Indigo Serever, re-started it, re-installed the plugin which still had all the correct config data for the plugin, and now it’s working. 

Dunno what the problem was, but appreciate your hanging with me while I got it to work.  Is it possible Indgio caches some of the plugin data? I DID have an older API and user key but changed all that today, but am thinking some of that data was cached in Indigo so it wasn’t recognizing the new keys?  Dunno… just thinking out loud….

Thanks!

 Jeffrey

**Comment by FlyingDiver** [comment]
Yeah, that shouldn't happen but I've seen weirder things.
