### ISSUE TITLE
First time run bug

### ISSUE THREAD

**Issue by indigo-jay** [IndigoDomotics/indigo-pushover#38]
When the plugin is installed for the first time the user will get the following error (despite entering the required keys in the config dialog):

     Pushover Error  Post Error - Result: {"token":"invalid","errors":["application token must be supplied, see https://pushover.net/api"],"status":0,"request":"e5d40fc7-35ad-423b-9a66-8ea533324866"}

So, when entering the keys in the config that popups up just after installing on a server that it's never been installed on, the key somehow isn't actually accessible until you restart the plugin.

**Comment by jcs** [comment]
Does `closedPrefsConfigUi` need to update `self.apiToken` from `valuesDict`?

**Comment by FlyingDiver** [comment]
Yup
