### ISSUE TITLE
Problem with variables

### ISSUE THREAD

**Issue by richosad** [IndigoDomotics/indigo-pushover#8]
Unfortunately I have problems with variables. If I insert it either in the title or body Pushover plugin hangs for a while and I get the following message in the log:

Error (client)                  timeout waiting for plugin response from io.thechad.indigoplugin.pushover for request UiGetValues2
  Error (client)                  timeout waiting for plugin response from io.thechad.indigoplugin.pushover for request CallPluginFunc
  Error (client)                  dialogForActionId() caught exception: NSInvalidArgumentException -- **\* -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

**Comment by discgolfer1138** [comment]
thanks for the thorough bug report, I'll take a look as soon as I can

**Comment by FlyingDiver** [comment]
Cannot reproduce.
